# CDKey SDK Server Makefile
# Copyright 2004 GameSpy Industries

PROJECT=gcdkeyserver

PROG_OBJS = \
	../../../nonport.o\
	../../../md5c.o\
	../../../common/gsAvailable.o\
	../../gcdkeyc.o\
	../../gcdkeys.o\
	../../gcdkeyservertest.o

#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
