#include "VoxMan.h"

STRUCT_INFO_BEGIN(SVoxelChunkVer3)
	STRUCT_VAR_INFO(nChunkVersion, TYPE_INFO(int))
	STRUCT_VAR_INFO(vOrigin, TYPE_INFO(Vec3i))
	STRUCT_VAR_INFO(vSize, TYPE_INFO(Vec3i))
	STRUCT_VAR_INFO(nFlags, TYPE_INFO(uint))
	STRUCT_VAR_INFO(m_arrVolume, TYPE_ARRAY(32, TYPE_ARRAY(32, TYPE_ARRAY(32, TYPE_INFO(ushort)))))
	STRUCT_VAR_INFO(m_arrSurfaceNames, TYPE_ARRAY(16, TYPE_ARRAY(64, TYPE_INFO(char))))
	STRUCT_VAR_INFO(m_arrColors, TYPE_ARRAY(32, TYPE_ARRAY(32, TYPE_ARRAY(32, TYPE_INFO(ColorB)))))
STRUCT_INFO_END(SVoxelChunkVer3)

STRUCT_INFO_BEGIN(SVoxelChunkVer4)
	STRUCT_VAR_INFO(nChunkVersion, TYPE_INFO(int))
	STRUCT_VAR_INFO(vOrigin, TYPE_INFO(Vec3i))
	STRUCT_VAR_INFO(vSize, TYPE_INFO(Vec3i))
	STRUCT_VAR_INFO(nFlags, TYPE_INFO(uint))
	STRUCT_VAR_INFO(m_arrSurfaceNames, TYPE_ARRAY(16, TYPE_ARRAY(64, TYPE_INFO(char))))
STRUCT_INFO_END(SVoxelChunkVer4)

