# GameSpy Presence & Messaging SDK Makefile - Mac OSX
# Copyright 2006 GameSpy Industries

PROJECT=gptestc

PROG_OBJS = \
	../../../md5c.o\
	../../../darray.o\
	../../../hashtable.o\
	../../../common/gsAvailable.o\
	../../../common/gsDebug.o\
	../../../common/gsStringUtil.o\
	../../../common/gsPlatform.o\
	../../../common/gsPlatformSocket.o\
	../../../common/gsPlatformThread.o\
	../../../common/gsPlatformUtil.o\
	../../../common/gsMemory.o\
	../../../common/macosx/MacOSXCommon.o\
	../../../common/gsTestMain.o\
	../../gp.o\
	../../gpi.o\
	../../gpiBuddy.o\
	../../gpiBuffer.o\
	../../gpiCallback.o\
	../../gpiConnect.o\
	../../gpiInfo.o\
	../../gpiOperation.o\
	../../gpiPeer.o\
	../../gpiProfile.o\
	../../gpiSearch.o\
	../../gpiUnique.o\
	../../gpiUtility.o\
	../../gpiTransfer.o\
	../gptestc.o


#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
