# Persistent Storage SDK Makefile
# Copyright 2004 GameSpy Industries

PROJECT=persisttest

PROG_OBJS = \
	../../../nonport.o\
	../../../hashtable.o\
	../../../darray.o\
	../../../md5c.o\
	../../../common/gsAvailable.o\
	../../../common/gsStringUtil.o\
	../../gstats.o\
	../../gbucket.o\
	../persisttest.o


#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
