STRUCT_INFO_BEGIN(StatInstGroupChunk)
	STRUCT_VAR_INFO(nDummy_pStatObj, TYPE_INFO(int))
	STRUCT_VAR_INFO(szFileName, TYPE_ARRAY(256, TYPE_INFO(char)))
	STRUCT_VAR_INFO(bHideability, TYPE_INFO(bool))
	STRUCT_VAR_INFO(bHideabilitySecondary, TYPE_INFO(bool))
	STRUCT_VAR_INFO(bPickable, TYPE_INFO(bool))
	STRUCT_VAR_INFO(fBending, TYPE_INFO(float))
	STRUCT_VAR_INFO(bComplexBending, TYPE_INFO(bool))
	STRUCT_VAR_INFO(bCastShadow, TYPE_INFO(bool))
	STRUCT_VAR_INFO(bRecvShadow, TYPE_INFO(bool))
	STRUCT_VAR_INFO(bPrecShadow, TYPE_INFO(bool))
	STRUCT_VAR_INFO(bUseAlphaBlending, TYPE_INFO(bool))
	STRUCT_VAR_INFO(fSpriteDistRatio, TYPE_INFO(float))
	STRUCT_VAR_INFO(fShadowDistRatio, TYPE_INFO(float))
	STRUCT_VAR_INFO(fMaxViewDistRatio, TYPE_INFO(float))
	STRUCT_VAR_INFO(fBrightness, TYPE_INFO(float))
	STRUCT_VAR_INFO(bUseSprites, TYPE_INFO(bool))
	STRUCT_VAR_INFO(bFadeSize_not_used, TYPE_INFO(bool))
	STRUCT_VAR_INFO(bRandomRotation, TYPE_INFO(bool))
	STRUCT_VAR_INFO(nMaterialLayers, TYPE_INFO(uchar))
	STRUCT_VAR_INFO(fDensity, TYPE_INFO(float))
	STRUCT_VAR_INFO(fElevationMax, TYPE_INFO(float))
	STRUCT_VAR_INFO(fElevationMin, TYPE_INFO(float))
	STRUCT_VAR_INFO(fSize, TYPE_INFO(float))
	STRUCT_VAR_INFO(fSizeVar, TYPE_INFO(float))
	STRUCT_VAR_INFO(fSlopeMax, TYPE_INFO(float))
	STRUCT_VAR_INFO(fSlopeMin, TYPE_INFO(float))
	STRUCT_VAR_INFO(nFlagsAndMaterialId, TYPE_INFO(int))
	STRUCT_VAR_INFO(m_dwRndFlags, TYPE_INFO(int))
STRUCT_INFO_END(StatInstGroupChunk)

STRUCT_INFO_BEGIN(SBrushTypeChunk)
	STRUCT_VAR_INFO(nDummy_pStatObj, TYPE_INFO(int))
	STRUCT_VAR_INFO(szFileName, TYPE_ARRAY(256, TYPE_INFO(char)))
STRUCT_INFO_END(SBrushTypeChunk)

STRUCT_INFO_BEGIN(SMatInfoTmp)
	STRUCT_VAR_INFO(nDummy, TYPE_INFO(int))
	STRUCT_VAR_INFO(szMatName, TYPE_ARRAY(256, TYPE_INFO(char)))
STRUCT_INFO_END(SMatInfoTmp)

