#include "Cry_Vector3.h"

STRUCT_INFO_T_BEGIN(Vec3_tpl, typename, F)
STRUCT_VAR_INFO(x, TYPE_INFO(F))
STRUCT_VAR_INFO(y, TYPE_INFO(F))
STRUCT_VAR_INFO(z, TYPE_INFO(F))
STRUCT_INFO_T_END(Vec3_tpl, typename, F)

STRUCT_INFO_T_BEGIN(Vec4_tpl, typename, F)
STRUCT_VAR_INFO(x, TYPE_INFO(F))
STRUCT_VAR_INFO(y, TYPE_INFO(F))
STRUCT_VAR_INFO(z, TYPE_INFO(F))
STRUCT_VAR_INFO(w, TYPE_INFO(F))
STRUCT_INFO_T_END(Vec4_tpl, typename, F)

STRUCT_INFO_T_BEGIN(Ang3_tpl, typename, F)
STRUCT_VAR_INFO(x, TYPE_INFO(F))
STRUCT_VAR_INFO(y, TYPE_INFO(F))
STRUCT_VAR_INFO(z, TYPE_INFO(F))
STRUCT_INFO_T_END(Ang3_tpl, typename, F)

STRUCT_INFO_T_BEGIN(Plane_tpl, typename, F)
STRUCT_VAR_INFO(n, TYPE_INFO(Vec3_tpl<F>))
STRUCT_VAR_INFO(d, TYPE_INFO(F))
STRUCT_INFO_T_END(Plane_tpl, typename, F)
