# ServerBrowsing SDK Makefile
# Copyright 2004 GameSpy Industries

PROJECT=sbctest

PROG_OBJS = \
	../sbctest.o\
	../../../nonport.o \
	../../../darray.o\
	../../../hashtable.o\
	../../../common/gsStringUtil.o\
	../../../common/gsAvailable.o\
	../../sb_crypt.o\
	../../sb_queryengine.o\
	../../sb_server.o\
	../../sb_serverbrowsing.o\
	../../sb_serverlist.o\
	../../../qr2/qr2regkeys.o

#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
