# P&T SDK Makefile
# Copyright 2004 GameSpy Industries

PROJECT=pttestc

PROG_OBJS = \
	../../../nonport.o\
	../../../darray.o\
	../../../common/gsAvailable.o\
	../../../common/gsStringUtil.o\
	../../../ghttp/ghttpBuffer.o\
	../../../ghttp/ghttpCallbacks.o\
	../../../ghttp/ghttpConnection.o\
	../../../ghttp/ghttpMain.o\
	../../../ghttp/ghttpProcess.o\
	../../../ghttp/ghttpCommon.o\
	../../../ghttp/ghttpPost.o\
	../../ptMain.o\
	../$(PROJECT).o


#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
