# HTTP SDK Makefile
# Copyright 2004 GameSpy Industries

PROJECT=ghttpc

PROG_OBJS = \
	../../../nonport.o\
	../../../darray.o\
	../../../md5c.o\
	../../../common/gsCrypt.o\
	../../../common/gsLargeInt.o\
	../../../common/gsRC4.o\
	../../../common/gsSHA1.o\
	../../../common/gsSSL.o\
	../../../common/gsStringUtil.o\
	../../ghttpBuffer.o\
	../../ghttpCallbacks.o\
	../../ghttpConnection.o\
	../../ghttpEncryption.o\
	../../ghttpMain.o\
	../../ghttpProcess.o\
	../../ghttpCommon.o\
	../../ghttpPost.o\
	../ghttpc.o

#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
