# Chat SDK Makefile
# Copyright 2004 GameSpy Industries

PROJECT=chatc

PROG_OBJS = \
	../../../nonport.o\
	../../../darray.o\
	../../../hashtable.o\
	../../../md5c.o\
	../../../common/gsStringUtil.o\
	../../chatCallbacks.o\
	../../chatCrypt.o\
	../../chatChannel.o\
	../../chatHandlers.o\
	../../chatMain.o\
	../../chatSocket.o\
	../chatc.o

#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
