# Query & Reporting 2 SDK Makefile
# Copyright 2004 GameSpy Industries

PROJECT=qr2csample

PROG_OBJS = \
	../../../nonport.o\
	../../../common/gsStringUtil.o\
	../../qr2.o\
	../../qr2regkeys.o\
	../qr2csample.o

#Include the stuff common to the GameSpy.net SDKs
include ../../../common/macosx/Makefile.common
